name: dev Hyeongwon Python package

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python main.py
      - name: Build and publish Python package
        run: |
          python -m pip install --upgrade build twine
          python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: saas-weather-application
          path: dist/

  push-docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: saas-weather-application
          path: dist

      # Docker Hub에 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HYEONGWON_DOCKER_USERNAME }}
          password: ${{ secrets.HYEONGWON_DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # Docker 이미지 빌드
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yosigoon/saas-weather:saas-weather-application-release-dev_hyeongwon-${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  update-deployment:
    needs: push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout saas-kubernetes repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HYEONGWON_GITHUB_TOKEN }}
          repository: 'saas-in-the-well/saas-kubernetes'
          ref: 'develop'

      # 최신 코드 pull 받기
      - name: Pull Latest Code
        run: |
          git pull origin dev_hyeongwon
      # 쿠버네티스 배포이미지 업데이트
      - name: Update Kubernetes Deployment Image
        run: |
          sed -i 's|yosigoon/saas-weather:.*|yosigoon/saas-weather:saas-weather-application-release-dev_hyeongwon-${{ github.sha }}|' ./kube/saas-weather-deployment.yaml
          git config --global user.name "HW_GithubAction"
          git config --global user.email "yosigoon@gmail.com"
          git add ./kube/saas-weather-deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin develop