name: saas-weather application deploy

on:
  push:
    branches: [ 'dev_jaeho' ]
  pull_request:
    branches: [ 'dev_jaeho' ]

permissions:
  id-token: write

env:
  APP_NAME: saas-weather
  BRANCH_NAME: develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_OIDC_ROLE}}
          role-session-name: ecrRoleSession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build . -t ${{ secrets.AWS_ECR_URL }}/${{ env.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ github.sha }} --build-arg VERSION=${{ github.sha }}
          docker push ${{ secrets.AWS_ECR_URL }}/${{ env.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ github.sha }}


      - name: checkout saas-kubernetes
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SAAS_GITHUB_TOKEN }}
          repository: ${{vars.SAAS_KUBE_REPOSITORY}}
          ref: ${{ env.BRANCH_NAME }}

      - name: Update kubernetes manifest
        run: |
          git fetch
          git checkout ${{ env.BRANCH_NAME }}
          git pull --rebase origin ${{ env.BRANCH_NAME }}
          
          sed -i 's|${{ secrets.AWS_ECR_URL }}/${{ env.APP_NAME }}:.*|${{ secrets.AWS_ECR_URL }}/${{ env.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ github.sha }}|' kube/${{ env.BRANCH_NAME }}/${{ env.APP_NAME }}.yaml
          git config user.email ${{ vars.SAAS_GITHUB_EMAIL }}
          git config user.name ${{ vars.SAAS_GITHUB_NAME }}
          git add kube/${{ env.BRANCH_NAME }}/${{ env.APP_NAME }}.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin ${{ env.BRANCH_NAME }}