name: GitHub Actions
run-name: Main GitHub Actions
on:
  push:
    branches: [ "dev_byeonggyu" ]

permissions:
      id-token: write

env:
  APP_NAME: saas-weather
  BRANCH_NAME: dev_byeonggyu
  ECR_REPOSITORY: saas-weather

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
         
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            role-to-assume: ${{secrets.AWS_OIDC_ROLE}}
            role-session-name: ecrRoleSession
            aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    #   - name: Build, tag, and push image to Amazon ECR
    #     id: build-image
    #     env:
    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #       IMAGE_TAG: ${{ github.sha }}
    #     run: |
    #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    #       echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        
      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AWS_ECR_URL }}/${{ env.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ github.sha }}  
          platforms: linux/amd64,linux/arm64

      - name: checkout saas-kubernetes
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SAAS_GITHUB_TOKEN }}
          repository: ${{vars.SAAS_KUBE_REPOSITORY}}
          ref: ${{ env.BRANCH_NAME }}

      - name: Update kubernetes manifest
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}
        run: |
          git fetch
          git checkout ${{ env.BRANCH_NAME }}
          git pull --rebase origin ${{ env.BRANCH_NAME }}
          sed -i 's/image:.*/image: ${{env.ECR_REGISTRY}}\/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}/g' ./kube/byeonggyu/${{env.APP_NAME}}.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "byeonggyu.jeon@bespinglobal.com"
          git add ./kube/byeonggyu/${{env.APP_NAME}}.yaml
          git commit -m 'update manifest'
          git push origin ${{ env.BRANCH_NAME }}