name: GitHub Actions
run-name: Main GitHub Actions
on:
  push:
    branches: [ "dev_byeonggyu" ]

env:
  APP_NAME: saas-weather

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Extract branch name
        id: vars
        shell: bash
        run: echo "::set-output name=dt::$(echo `date +%s`)"

      - name: Build and Push the Docker image
        run: |
          docker build . -t ${{secrets.BYEONGGYU_DOCKER_NAME}}/${{secrets.BYEONGGYU_DOCKER_REPO}}:${{steps.vars.outputs.dt}}
          docker login -u${{secrets.BYEONGGYU_DOCKER_ID}} -p${{secrets.BYEONGGYU_DOCKER_PW}}
          docker push ${{secrets.BYEONGGYU_DOCKER_NAME}}/${{secrets.BYEONGGYU_DOCKER_REPO}}:${{steps.vars.outputs.dt}}


  git-remote-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout saas-kubernetes
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BYEONGGYU_GITHUB_TOKEN }}
          repository: 'saas-in-the-well/saas-kubernetes'
        
      
      - name: Update kubernetes manifest
        run: |
          git fetch
          git chekout dev_byeonggyu
          git pull --rebase origin dev_byeonggyu
          sed -i 's/image:.*/image: ${{secrets.BYEONGGYU_DOCKER_NAME}}\/${{secrets.BYEONGGYU_DOCKER_REPO}}:${{steps.vars.outputs.dt}}/g' kube/weather-deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email ${{secrets.BYEONGGYU_EMAIL}}
          git add kube/byeonggyu/${{env.APP_NAME}}.yaml
          git commit -m 'update manifest'
          git push origin dev_byeonggyu
